#!/bin/sh

# uci set wireless.default_radio0.ssid=OpenWrt-$(cat /sys/class/ieee80211/phy0/macaddress|awk -F ":" '{print $5""$6 }' | tr 'a-z' 'A-Z')-2.4G
# uci set wireless.default_radio1.ssid=OpenWrt-$(cat /sys/class/ieee80211/phy0/macaddress|awk -F ":" '{print $5""$6 }' | tr 'a-z' 'A-Z')-5G
# uci set wireless.radio0.channel='9'
uci set wireless.radio1.channel='149'
uci set wireless.default_radio0.ssid=OpenWrt-2.4G
uci set wireless.default_radio0.encryption='psk2+ccmp'
uci set wireless.default_radio0.key='password'
uci set wireless.default_radio1.ssid=OpenWrt-5G
uci set wireless.default_radio1.encryption='psk2+ccmp'
uci set wireless.default_radio1.key='password'
uci commit wireless

# 设置所有网口可访问网页终端
uci delete ttyd.@ttyd[0].interface

# 设置所有网口可连接 SSH
uci set dropbear.@dropbear[0].Interface=''

uci commit

#sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow
#sed -i 's/root:::0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow

sed -ri '/check_signature/s@^[^#]@#&@' /etc/opkg.conf
sed -i 's#downloads.immortalwrt.org#mirrors.pku.edu.cn/immortalwrt#g' /etc/opkg/distfeeds.conf

/etc/init.d/network restart

exit 0
